### ISSUE TITLE
Error on page 132

### ISSUE THREAD

**Issue by leongaban** [scotch-io/mean-machine-code#10]
In the Angular chapter about Configuring Routes

// inject ngRoute for all our routing needs
`angular.module('routerRoutes', ['ngRoute'])`

Should be `'routerApp'` since that was the name of the app already set in the example.

**Comment by chris-sev** [comment]
The `routerRoutes` and `routerApp` are two different Angular modules.

`routerRoutes` will be injected into `routerApp` in the main `app.js` file.

https://github.com/scotch-io/mean-machine-code/blob/master/12-angular-routing/public/js/app.js#L1
