### ISSUE TITLE
17- User CRM Login name cached

### ISSUE THREAD

**Issue by franzsilva** [scotch-io/mean-machine-code#13]
Hello, 

If you login with one account it shows the username perfectly but if you log out and login back with a different user without closing the browser it shows the user that was logged in before, forcing to press F5 then shows the user correctly, im guessing its not refreshing the view.

**Comment by justinpage** [comment]
@franzsilva you can set `vm.user = ''`which does the trick, not sure if it's the best method but it's a suggestion.

**Comment by yonasstephen** [comment]
setting `vm.user = ''` at logout does not seem to fix the cache. I got the latest copy of code and this bug still persists..

**Comment by justinpage** [comment]
@yonasstephen use this as an alternative reference: 
https://github.com/KLVTZ/MeanMachine/tree/master/10.user-manag-crm

**Comment by yonasstephen** [comment]
hey thanks! that version definitely works :) do you mind explaining shortly what was the fix? bcos my version also had the `vm.user = ''` at logout, but doesn't work.

**Comment by justinpage** [comment]
@yonasstephen that's difficult to say without seeing your code. My best suggestion is to `diff` your angular controllers and services to the repo above and the code examples in the book. My guess is something was overlooked.

**Comment by yonasstephen** [comment]
I spotted the issue, it's the cache for /api/me should be set to false `return $http.get('/api/me', { cache: false });`

**Comment by justinpage** [comment]
@yonasstephen :+1: glad you found it!

**Comment by mir4ef** [comment]
Yes, setting the cache to false works, but I think a better approach will be to cache the info and clear it on logout:

``` javascript
vm.doLogout = function () {
        // logout code
        $cacheFactory.get('$http').remove('/api/me');
    };
```

You would need to inject `$cacheFactory` into your controller though. Just my 2 cents :)
