### ISSUE TITLE
19-mean-workflow gulp 'scripts' & 'angular' tasks redundant by accident?

### ISSUE THREAD

**Issue by metaColin** [scotch-io/mean-machine-code#19]
I have a question about 2 gulp tasks that seem appear to be (partially) redundant:

Both the 'scripts' and the 'angular' tasks grab js files from the same location, and in fact the only difference between these two tasks is the 'angular' task includes ngAnnotate in it's pipeline.

I'm a little confused, could this be a mistake?

If I am reading the book right the all.js file generated by the 'scripts' task is supposed to contain all of our front end Angular files, and the app.js file generated by the 'angular' task should contain our angular libs. If that is the case shouldn't the 'angular' task be grabbing js files from inside of the assets folder instead of the app folder?

**Comment by chris-sev** [comment]
The tasks were meant to be examples of different kinds of tasks. They are redundant and probably shouldn't be used together in the same project.

Just wanted to provide a few different tasks in case you wanted to pick and choose for your own projects.
