### ISSUE TITLE
Bug in page 131 of book

### ISSUE THREAD

**Issue by Zyst** [scotch-io/mean-machine-code#2]
Hello guys!

I'm currently eating through the book at an unhealthy pace. It's a truly awesome book, love your work.

Anyhow, found a small bug in page 131

Screenshot of the page:

![image](https://cloud.githubusercontent.com/assets/3832380/5715011/bba77cc6-9a97-11e4-9ac0-6f654cce2245.png)

At this point you guys mention it should work, however it won't because earlier you configured `server.js` to handle all `GET` requests and direct them to `index.html`:

![image](https://cloud.githubusercontent.com/assets/3832380/5715020/f1125cfa-9a97-11e4-8096-a54bfdb5246d.png)

And then from that point until the first screenshot you don't edit `server.js` again, which means that when the browser requests the `app.js` and `app-routes.js` with a `GET` request it gets served `index.html` instead of our javascript files. 

To solve this I went into my `server.js` and edited it a bit like so:

```
// Set the public folder to serve public assets
app.use(express.static(__dirname + "/public/views"));

// Set up our one route to the index.html file
app.get("/", function(req, res) {
    res.sendFile(path.join(__dirname + "/public/views/index.html"));
});
```

Just a small comment, figured you might want to know and I figure you do change it a after that screenshot (In page 131). But since you show working screenshots and the site itself won't work at that point that might be disconcerting for less technically inclined users.

Thanks for writing this book, it's truly amazing.

Will keep eating through the book, and report if I find anything similar again, have a great day!

**Comment by Zyst** [comment]
Downloaded your code sample, and it works as you guys have it. 

Sorry for the false alarm!

Great day.

**Comment by hollylawly** [comment]
Good catch! There was a bit of disconnect in some parts between the sample
code repo and the directions in the book because we had to go back and
forth a few times to change some things. I'll go through again and make
sure everything matches. Thanks for reading and we're glad you're enjoying
it!

**Comment by Zyst** [comment]
Nope! The sample, and the book are correct, I just got the file structure wrong. I put my JS folder inside the views.

Sorry for the mix up.
