### ISSUE TITLE
10-node-authentication route middleware prevents user creation 

### ISSUE THREAD

**Issue by erikanderson** [scotch-io/mean-machine-code#20]
I might be wrong but shouldn't the block which begins like this to create a user:

``` javascript
// on routes that end in /users
// ----------------------------------------------------
apiRouter.route('/users')

    // create a user (accessed at POST http://localhost:8080/users)
    .post(function(req, res) {
```

be placed before the route middleware to verify a token? :

**Comment by chris-sev** [comment]
That was placed after the token verification because we want to be sure a user is authenticated before they create other users.

**Comment by erikanderson** [comment]
That makes sense. I guess if you wanted to make this a part of another app you would just move that post logic before it then. 

Great book by the way!
