### ISSUE TITLE
Chapter 17: Login to database fails...

### ISSUE THREAD

**Issue by JESii** [scotch-io/mean-machine-code#23]
Attempting to run the Chapter 17 / CRM code results in 
     "Authentication failed. User not found."

config.js / database => 'mongodb://node:noder@novus.modulusmongo.net:27017/Iganiq8o'

**Comment by chris-sev** [comment]
People seem to be deleting the main user from the test database. I've added a new button at the login screen to add the test user back to the database quickly. Try logging in now.

**Comment by JESii** [comment]
Works! Thanks much.
