### ISSUE TITLE
Chapter 9 - TypeError: object is not a function

### ISSUE THREAD

**Issue by jim-at-jibba** [scotch-io/mean-machine-code#25]
Have worked through to this point with no problems. I have checked my code against this repo and it match but I have getting the following error:

TypeError: object is not a function

![screen shot 2015-04-11 at 2 58 41 pm](https://cloud.githubusercontent.com/assets/7897877/7100715/5a695290-e05b-11e4-9dec-12e381595921.png)

This is refering to this line of code:

```
var user = new User();
```

Any help would be much appreciated. Thanks for the great book by the way.

James

**Comment by jim-at-jibba** [comment]
Anyone??

**Comment by Randore** [comment]
Post your code, not the screen shot. I have not read upto chapt 9 but someone will help if you post the code. And check if there is any issue with case-sensitive.

**Comment by chris-sev** [comment]
I just pulled down the code and it seems to be working fine for me:

![](https://cask.scotch.io/2015/04/postman.png)

Double check to make sure that all your Mongoose models are correct. Passing objects around the various Node files with module.exports, can be tricky with the syntax. This is essentially saying that you are trying to call a function or object incorrectly.

And yes, a link to a code repo helps.

**Comment by jim-at-jibba** [comment]
OK I will take a look. Thanks for the reply.

**Comment by jim-at-jibba** [comment]
Was a typo on my side. Sorry.
