### ISSUE TITLE
Chapter 17: Login to database fails again

### ISSUE THREAD

**Issue by StackBlaster** [scotch-io/mean-machine-code#28]
it appears issue #23 is active again. I read you added a new button but I don't see where this is on the view.
![17-user-crm](https://cloud.githubusercontent.com/assets/1755616/7844782/f905b990-0480-11e5-8e07-e4df9d699c89.jpg)

**Comment by chris-sev** [comment]
Added the button and the create sample user api stuff. Try that now.

**Comment by StackBlaster** [comment]
Please note, I am aware the casing on the fields are title-cased, this was merely the last few attempts. I had already tried with { 'name': 'Chris', 'username': 'chris', 'password': 'supersecret' }

**Comment by StackBlaster** [comment]
ok, this now works again. issue can be closed.
