### ISSUE TITLE
Cannot find module .app/modules/user

### ISSUE THREAD

**Issue by cpheimbach** [scotch-io/mean-machine-code#35]
Dear all,

I tried to find a solution for the below error 

but no success so far unfortunately. I have cloned the repo and compared the provided code with mine but can't spot the problem. I also checked the access rights of folders and all but I'm stuck. I am just starting with coding so if you have further general advice how to best debug please feel free to add this to your answer. Cheers!

module.js:339
    throw err;
    ^

Error: Cannot find module './app/models/user'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/cph/Public/Coding/hacks/actioncy-learn-to-code/app/server.js:10:18)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:136:18)
    at node.js:972:3

**Comment by cpheimbach** [comment]
zzzZZZZZzzzzzZZZZZZZ

**Comment by josephkandi** [comment]
@cpheimbach Do you have a link to the code you are having issues with?

**Comment by cpheimbach** [comment]
[app.zip](https://github.com/scotch-io/mean-machine-code/files/83844/app.zip)

@josephkandi Hi Joseph, thank you very much for having a look at my code. I attached a zip file with all I have done following the instructions. 

Christian

**Comment by josephkandi** [comment]
@cpheimbach Change this line from
`var User       = require('./app/models/user');` 

to

`var User       = require('./models/user');`

The issue is the **models** folder is in the same folder path as your `serve.js` file. So the right way will be to use the `./`, the path will be relative to the `server.js` file.

**Comment by cpheimbach** [comment]
@josephkandi Hey mate, thank you very much! It works and I couldn't have done it without your help. I am a newbie as you can tell and I still trip over these small but crucial mistakes. Thank you for have taking the time. Let me know if I can return the favour. I am a marketer by craft so if you need assist in that area ping me a message. Now I can continue the course. Cheers!

**Comment by jehovahcreations** [comment]
Check this, briefly explained here, and you can fix it https://youtu.be/idJHHxA02l8
