### ISSUE TITLE
Issue with pg. 132 Routing

### ISSUE THREAD

**Issue by erikjenks** [scotch-io/mean-machine-code#36]
I am currently going through your tutorial (fantastic by the way), and I have stumbled upon this issue. 

![screen shot 2016-01-05 at 8 59 54 am](https://cloud.githubusercontent.com/assets/7226787/12116864/d3ef3e38-b38a-11e5-8cd4-19943e3da740.png)

As you can see I am receiving this error that 'routerRoutes is not defined'. Now I had gone through and typed out the code, and then I copy and pasted yours to see if this error persisted. I have made sure to check that all of my files and folders are in the right location. 

Any recommendations? Or skip ahead and go to the next section?

**Comment by chris-sev** [comment]
Do you have a link to the code that I can browse in a GitHub repo? What's the code in your `angular-route.js` file look like?

**Comment by erikjenks** [comment]
do you mean the `app.routes.js` file? The repo can be found here https://github.com/erikjenks/angular_route_practice, but here is the contents of the `app.routes.js` file for you.

```
// inject ngRoute for all our routing needs
angular.module('routerRoutes', ['ngRoute'])

// configure our routes
.config(function($routeProvider, $locationProvider) {
    $routeProvider

        // route for the home page
        .when('/', {
            templateUrl : 'views/pages/home.html',
            controller  : 'homeController',
            controllerAs: 'home'
        })

        // route for the about page
        .when('/about', {
            templateUrl : 'views/pages/about.html',
            controller  : 'aboutController',
            controllerAs: 'about'
        })

        // route for the contact page
        .when('/contact', {
            templateUrl : 'views/pages/contact.html',
            controller  : 'contactController',
            controllerAs: 'contact'
        });

    $locationProvider.html5Mode(true);
});
```

**Comment by adocomplete** [comment]
From looking at your code it looks like you don't have the routerRoutes dependency correctly wrapped.

should be

angular.module('routerApp', ['routerRoutes'])...
instead of 

angular.module('routerApp', [routerRoutes])...

**Comment by erikjenks** [comment]
I thought that was the issue as well, but looking at my code in the `app.js` file I have it wrapped in square brackets and single quotes, but the error is still coming through as if I do not. Thats the reason I asked, I am stumped. Thanks for all the help

**Comment by josephkandi** [comment]
@erikjenks Its the ['routerRoutes'] and also if you check the javascript console in Chrome you will 2 errors, the one is it can't load the module and the other your catch all route in express points to the wrong location for the index.html file. I have got your code working on my machine

**Comment by erikjenks** [comment]
Thanks for the help. I got it to work with @josephkandi help
