### ISSUE TITLE
'username not found' in chapter 10

### ISSUE THREAD

**Issue by Lgofk** [scotch-io/mean-machine-code#39]
First, I writhe all the code myself, than I tryed to copy it from the book but the problem doesn't go away :(

```
apiRouter.post('/authenticate', function (req, res) {
    // find the user
    User.findOne({
        username: req.body.username
    }).select('name username password').exec(function (err, user) {

        if (err) throw err;

        // no user with that username was found
        if (!user) {
            res.json({
                success: false,
                message: 'Authentication failed. User not found.'
            });
        } else if (user) {

            // check if password matches
            var validPassword = user.comparePassword(req.body.password);
            if (!validPassword) {
                res.json({
                    success: false,
                    message: 'Authentication failed. Wrong password.'
                });
            } else {

                // if user is found and password is right
                // create a token
                var token = jwt.sign({
                    name: user.name,
                    username: user.username
                }, superSecret, {
                    expiresInMinutes: 1440 // expires in 24 hours
                });

                // return the information including token as JSON
                res.json({
                    success: true,
                    message: 'Enjoy your token!',
                    token: token
                });
            }
        }
    });
});
```

![image](https://cloud.githubusercontent.com/assets/13064036/15273600/d6efb958-1aa7-11e6-8fe7-046ea89053b2.png)

username and password are correct.

Also I found out that the findOne method returns 'null'.

**Comment by FNGR2911** [comment]
how du you get it work? getting the some error all the time :(

**Comment by chris-sev** [comment]
What database are you using? Are you sure that the user you're trying to login with is in there?

Too many people abused the database provided in the book, so you'll need to spin up your own either locally or on mlab.com or modulus.io.

**Comment by FNGR2911** [comment]
Hi @sevilayha: I got local mongodb working and checkt the database with Robomongo.  The creation of the user worked without a problem but when I try to find him like in the tutorial I always get the user not found :(

**Comment by erhv74** [comment]
that's looks like a deja-vu for me when i followed the examples. I think
was a problem with:

params.username
params.password

i changed to:

body.username
body.password

something like that,
