### ISSUE TITLE
expiresInMinutes is deprecated

### ISSUE THREAD

**Issue by yacafx** [scotch-io/mean-machine-code#40]
On API /authenticate method expiresInMinutes  is deprecated,  should use expiresIn expressed in seconds or a string describing a time span rauchg/ms. Eg: 60, "2 days", "10h", "7d"

The code should be: `expiresIn: "24h"`

https://github.com/auth0/node-jsonwebtoken

**Comment by chris-sev** [comment]
Fixed in the latest release.
