### ISSUE TITLE
Not working with UI-ROUTER

### ISSUE THREAD

**Issue by DespertaWeb** [scotch-io/mean-machine-code#43]
Hi! I'm new on MEAN Stack, I was trying to follow your e-book but I got stucked at the point of the Login button with AngularJS in the MEAN app: users manager chapter.

Untill then, evertihing was working just perfectly.

I'm following all the steps but with ui-router insted, I guess  this may cause some problems with the $http.post in here:
`   authFactory.login = function(username, password) {

```
    // return the promise object and its data
    return $http.post('/api/authenticate', {
        username: username,
        password: password
    })
        .then(function(data) {
            AuthToken.setToken(data.token);
            return data;
        });
};`
```

I really don't understand why the button doesn't do anything :(

any idea why could it be?  @sevilayha

**Comment by chris-sev** [comment]
What errors are you getting in your console?
