### ISSUE TITLE
login username on navbar

### ISSUE THREAD

**Issue by ffachrial** [scotch-io/mean-machine-code#50]
Hello,

After cloned and run this app, I found a bug: after login using username john and logout, re-login using different username jane will provide username john on navbar. It supposed to be username jane on navbar, isn't it? CMIIW

**Comment by ChillySpark** [comment]
@ffachrial 

The prior user is being cached. See authService.js...

return $http.get('/api/me', { cache: true });

changing to false works for me, see:

https://github.com/scotch-io/mean-machine-code/issues/13

**Comment by ffachrial** [comment]
@WebAppNut ,

Thank you for your info, so is not a bug. i will close this issue.
