### ISSUE TITLE
data binding not working in 17-user-crm

### ISSUE THREAD

**Issue by codelinq** [scotch-io/mean-machine-code#7]
on index.html, I have

``` html
<li ng-if="main.loggedIn" class="navbar-text">Hello {{ main.user.name }}!</li>
```

The navbar-text doesn't get updated after I login.

![users](https://cloud.githubusercontent.com/assets/191882/5970484/f37e05d0-a801-11e4-9467-3c7787a028a1.jpg)

However, if I click in the address bar and hit enter it does get updated.

![users 1](https://cloud.githubusercontent.com/assets/191882/5970490/1305cfa0-a802-11e4-9b1b-a9c540c31a11.jpg)

I thought maybe it was my code, so I downloaded your source and it does the same thing. 

Any ideas?

**Comment by chris-sev** [comment]
Looks like the check to see if a user is logged in and bind the new user data on every route change isn't doing its job.

https://github.com/scotch-io/mean-machine-code/blob/master/17-user-crm/public/app/controllers/mainCtrl.js#L10-L13

I'll be able to take a look at this further over the weekend. Will keep this updated.

**Comment by chris-sev** [comment]
Updated. User information is now updated after login:

Moved the check for the user info into the route `$rootScope.$on('routeChangeStart')`

Also added caching to the `getUser()` call in `AuthService.js`: 

```
return $http.get('/api/me', { cache: true });
```
