### ISSUE TITLE
17-user-crm clicking logout doesn't update ng-view when path is already "/"

### ISSUE THREAD

**Issue by codelinq** [scotch-io/mean-machine-code#8]
To recreate the issue follow these steps
1. Login and you are presented with the users page "/users"
2. Click on "User CRM" to be taken to "/"
3. Click Logout. Nothing appears to happen.
4. Force a refresh to see that you are logged out.

**Comment by chris-sev** [comment]
The solution for this would be to add some route middleware in the Angular routing to check if a user is already logged in. 

You could also use the same approach we've used in the code with the httpInterceptor. Check if a user is logged in there and prevent them from visiting the login page. 

This tutorial has some good (but more advanced) routing ideas including middleware: http://www.frederiknakstad.com/2013/08/04/authentication-in-single-page-applications-with-angular-js-part-2/
